In [121]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [122]:
df = pd.read_csv('155 sorted.csv')
df

yCO2  yH2S       yC1   yHC       yN2         TR     MWC7+     xvol.  \
0    0.000000    0.0  0.000000   0.0  0.000000  0.000000  0.000000  0.000000   
1    0.000000    0.0  0.000000   0.0  0.000000  0.000424  0.060175  0.000000   
2    0.142857    0.0  0.000000   0.0  0.000000  0.000933  0.105881  0.000000   
3    0.142857    0.0  0.000000   0.0  0.000000  0.010178  0.111208  0.004502   
4    0.142857    0.0  0.000000   0.0  0.000000  0.028838  0.132323  0.005232   
..        ...    ...       ...   ...       ...       ...       ...       ...   
150  1.000000    0.8  0.846296   0.8  0.052632  0.776081  0.578061  0.623996   
151  1.000000    0.9  1.000000   0.8  0.163158  0.776081  0.585616  0.632757   
152  1.000000    0.9  1.000000   0.8  0.226316  0.811705  0.649832  0.649306   
153  1.000000    1.0  1.000000   1.0  0.226316  0.905852  0.714048  0.798369   
154  1.000000    1.0  1.000000   1.0  1.000000  1.000000  1.000000  1.000000   

         xint    xC5-C6  Experimental MMP  
0    0.000000  0.000000          0.000000  
1    0.017940  0.000000          0.010395  
2    0.025249  0.000425          0.029106  
3    0.027021  0.000425          0.046035  
4    0.027021  0.001701          0.051084  
..        ...       ...               ...  
150  0.923145  0.500850          0.937927  
151  0.923145  0.500850          0.944164  
152  0.923145  0.648384          0.986932  
153  0.923145  1.000000          0.987823  
154  1.000000  1.000000          1.000000  

[155 rows x 11 columns]

In [123]:
X = df.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]].values
y = df.iloc[:, 10].values

In [124]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42)

In [125]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler() 
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)

In [126]:
from sklearn import svm
model = svm.SVR(kernel='linear')
model.fit(X_train, y_train)

SVR(kernel='linear')

In [127]:
y_pred = model.predict(X_test)
y_pred

array([0.39440162, 0.72506868, 0.24214567, 0.23170988, 0.53354453,
       0.33748737, 0.41835089, 0.80586537, 1.05776189, 0.35694904,
       0.28858758, 0.65125509, 0.39116785, 0.37953287, 0.16906253,
       0.19461449, 0.2377967 , 0.41512108, 0.53091756, 0.64434301,
       0.19349121, 0.15762094, 0.13591105, 0.21246414, 0.35989763,
       0.59736935, 0.42564049, 0.28987096, 0.3977089 , 0.3966764 ,
       0.56727209, 0.42815784, 0.54835518, 0.39501723, 0.47481576,
       0.35305214, 0.29619956, 0.2232618 , 0.62402266, 0.38558358,
       0.31149292, 0.27013965, 0.55967287, 0.20305137, 0.31099205,
       0.3976389 , 0.15392561, 0.70752212, 0.35429871, 0.54285637,
       0.2263871 , 0.39181536, 0.74364441, 0.28776979, 0.09623531])

In [128]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9301580915771495

In [129]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.003967437424750559


In [130]:
rmse = np.sqrt(mse)
rmse

0.06298759738829986

In [131]:
aape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
aape

29.929871962365223

In [132]:
ape = np.mean(((y_test - y_pred) / y_test)) * 100
ape

-23.484639324144975

In [133]:
support_vectors = model.support_vectors_
sp_155S = pd.DataFrame(support_vectors)
sp_155S

0    1         2    3         4         5         6         7  \
0  0.642857  0.0  0.000000  0.0  0.000000  0.086938  0.214974  0.088951   
1  1.000000  0.5  0.759259  0.4  0.052632  0.776081  0.555396  0.616817   
2  1.000000  0.0  0.500000  0.2  0.000000  0.726887  0.540286  0.616817   
3  1.000000  1.0  1.000000  1.0  1.000000  1.000000  1.000000  1.000000   

          8         9  
0  0.221484  0.139456  
1  0.772536  0.475340  
2  0.627907  0.431548  
3  1.000000  1.000000

In [134]:
sp_155S = sp_155S.to_csv('SP_155S.csv')

In [135]:
dual_coefficients = model.dual_coef_
dc_155S = pd.DataFrame(dual_coefficients)
dc_155S

0        1         2         3
0 -0.319925  0.27832  0.107011 -0.065406

In [136]:
dc_155S = dc_155S.to_csv('dc_155S.csv')

In [137]:
weights = np.dot(dual_coefficients, support_vectors)
weights

array([[ 0.11425899,  0.07375411,  0.19941667,  0.06732442, -0.05075724,
         0.20056442,  0.07821315,  0.14381516,  0.14594105,  0.06845585]])

In [138]:
intercept = model.intercept_
intercept

array([0.05896688])

In [139]:
bias = -intercept
bias

array([-0.05896688])

In [140]:
SVR_155S = pd.DataFrame({'Actual Values': y_test, 'Predicted value': y_pred})
SVR_155S

Actual Values  Predicted value
0        0.399465         0.394402
1        0.815860         0.725069
2        0.133353         0.242146
3        0.133056         0.231710
4        0.559252         0.533545
5        0.294030         0.337487
6        0.458568         0.418351
7        0.857440         0.805865
8        0.987823         1.057762
9        0.317493         0.356949
10       0.192753         0.288588
11       0.714286         0.651255
12       0.390258         0.391168
13       0.371844         0.379533
14       0.102465         0.169063
15       0.112860         0.194614
16       0.133353         0.237797
17       0.449361         0.415121
18       0.557173         0.530918
19       0.706267         0.644343
20       0.112563         0.193491
21       0.076032         0.157621
22       0.067716         0.135911
23       0.119988         0.212464
24       0.325215         0.359898
25       0.642115         0.597369
26       0.463023         0.425640
27       0.215028         0.289871
28       0.426492         0.397709
29       0.417648         0.396676
30       0.622810         0.567272
31       0.467478         0.428158
32       0.600238         0.548355
33       0.405702         0.395017
34       0.519454         0.474816
35       0.307395         0.353052
36       0.251856         0.296200
37       0.125928         0.223262
38       0.690823         0.624023
39       0.381942         0.385584
40       0.279477         0.311493
41       0.173745         0.270140
42       0.610336         0.559673
43       0.116127         0.203051
44       0.269676         0.310992
45       0.419958         0.397639
46       0.071874         0.153926
47       0.799822         0.707522
48       0.317493         0.354299
49       0.577666         0.542856
50       0.131868         0.226387
51       0.394119         0.391815
52       0.827146         0.743644
53       0.185625         0.287770
54       0.051084         0.096235

In [141]:
SVR_155S = SVR_155S.to_csv('SVR_155S.csv')

In [142]:
y_train_pred = model.predict(X_train)

In [143]:
# y_train_pred = pd.DataFrame({'Actual Values': y_train, 'Predicted value': y_train_pred})

In [144]:
# y_train_pred

In [145]:
# TRAIN_SVR_155S = y_train_pred.to_csv('TRAIN_SVR_155S.csv')

In [146]:
r2_score(y_train, y_train_pred)

0.9459822891361725

In [147]:
mse = mean_squared_error(y_train, y_train_pred)
mse

0.0034301193271048746

In [148]:
rmse = np.sqrt(mse)
rmse

0.058567220585450996